# Cargo configuration for matrices_evolved
# Basic performance optimizations

[build]
rustflags = [
    "-C", "opt-level=3",
    "-C", "target-cpu=native",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "opt-level=3",
    "-C", "target-cpu=native",
    "-C", "target-feature=+avx2,+fma,+bmi2",
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "opt-level=3", 
    "-C", "target-cpu=native",
    "-C", "target-feature=+neon",
]